// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsAdsOnZtw8WTdgFrzEXM9L7SxFQcYhEE',
    appId: '1:1038823222920:web:db2db43d397a7820b9b93d',
    messagingSenderId: '1038823222920',
    projectId: 'chat-app-694e5',
    authDomain: 'chat-app-694e5.firebaseapp.com',
    storageBucket: 'chat-app-694e5.firebasestorage.app',
    measurementId: 'G-BV4H9XHWQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdz2RSIhQhW0m3tQkAabSX13BXIxdYgYk',
    appId: '1:1038823222920:android:4fb54e4895aeb111b9b93d',
    messagingSenderId: '1038823222920',
    projectId: 'chat-app-694e5',
    storageBucket: 'chat-app-694e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1TPuwacv47_yjHVFvilB_gFJHUABuT-Q',
    appId: '1:1038823222920:ios:583fe0c3f542e9f8b9b93d',
    messagingSenderId: '1038823222920',
    projectId: 'chat-app-694e5',
    storageBucket: 'chat-app-694e5.firebasestorage.app',
    iosBundleId: 'com.example.scholarChatSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1TPuwacv47_yjHVFvilB_gFJHUABuT-Q',
    appId: '1:1038823222920:ios:583fe0c3f542e9f8b9b93d',
    messagingSenderId: '1038823222920',
    projectId: 'chat-app-694e5',
    storageBucket: 'chat-app-694e5.firebasestorage.app',
    iosBundleId: 'com.example.scholarChatSetup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsAdsOnZtw8WTdgFrzEXM9L7SxFQcYhEE',
    appId: '1:1038823222920:web:69139c02e31dc72db9b93d',
    messagingSenderId: '1038823222920',
    projectId: 'chat-app-694e5',
    authDomain: 'chat-app-694e5.firebaseapp.com',
    storageBucket: 'chat-app-694e5.firebasestorage.app',
    measurementId: 'G-ER1HRWL1ZK',
  );
}
